# Generated by Django 4.2.18 on 2025-09-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=50)),
                ("rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("listID", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("status", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
